matrix:
    include:
        - os: linux
          dist: bionic
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        # direct tests of facilities written in c++
        - language: cpp
          compiler:
              - gcc
          script:
              - mkdir ./cpp/tests/build
              - cd ./cpp/tests/build
              - cmake ..
              - make
              - ctest
        # python tests (this includes tests of c++ code if there is a python
        # interface for that code and a corresponding test)
        - language: python
          python: 3.7
          install:
              - pip install scipy
              - pip install .
          script:
              - cd khuri/tests/
              - pytest
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt update -q
    - sudo apt install libgsl-dev
    - sudo apt install libeigen3-dev
