language: cpp
compiler:
    # - clang
    - gcc
os: linux
dist: bionic

install:
    # - sudo apt install googletest
    - sudo apt install libgtest-dev

script:
    - mkdir ./tests/build
    - cd tests/build
    - cmake ..
    - make
    - ctest
