language: cpp
compiler:
    # - clang
    - gcc
os: linux
dist: bionic

before_install:
    - sudo add-apt-repository universe
    - sudo apt update -q
    - sudo apt install libgsl-dev

script:
    # python tests (this includes tests of c++ code if there is a python
    # interface for that code and a corresponding test)
    - pip install .
    - cd khuri/tests/
    - pytest
    # direct tests of facilities written in c++
    - cd ../..
    - mkdir ./tests/build
    - cd tests/build
    - cmake ..
    - make
    - ctest
