language: cpp
compiler:
    # - clang
    - gcc
os: linux
dist: bionic

before_install:
    - sudo add-apt-repository universe
    - sudo add-apt-repository universe/libdevel
    - sudo apt install libgsl-dev

script:
    - mkdir ./tests/build
    - cd tests/build
    - cmake ..
    - make
    - ctest
